name: NCDMV Reservation Check
on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 2 * * *'   # 10:00 PM and 10:30 PM Charlotte time
    - cron: '0,30 3 * * *'   # 11:00 PM and 11:30 PM
    - cron: '0,15,30,45 4 * * *'   # 12:00 AM and 12:30 AM
    - cron: '0,30 5 * * *'   # 1:00 AM and 1:30 AM
      # every hour
#    - cron: "0 * * * *"
jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: setup python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: install CLI tools
        run: |
          pipx install --python "$(which python3.12)" ncdmv-reservation
      - name: Send email
        shell: bash
        run: |
          echo "::group::NC DMV Driver License Office Availability"
          ncdmv-driver-license-office-availability | tee ncdmv.json
          echo "::endgroup::"
          AVAIL="$(<ncdmv.json jq '.[] | select(.office_name == "Monroe") | .is_reservable' -r)"
          MSG="Monroe is reservable: $AVAIL"
          echo "$MSG"
          # if false, don't exit 0
          if [[ "$AVAIL" == "false" ]]; then
            echo 'not sending email'
            exit 0
          fi
          curl -s --user "api:${{ secrets.MAILGUN_API_KEY }}" \
            https://api.mailgun.net/v3/${{ secrets.MAILGUN_DOMAIN }}/messages \
            -F from="${{ secrets.FROM_EMAIL }}" \
            -F to="${{ secrets.TO_EMAIL }}" \
            -F subject="$MSG" \
            -F text="This email was sent automatically from a GitHub Action!"          
